blueprint:
  name: Bind timer to Inovelli switch
  description: |
    Bind a Home Assistant timer entity to an Inovelli Blue Series switch.

    Version 2026.01.11.3
  domain: automation
  input:
    timer_entity:
      name: Timer entity
      description: "The entity that will be bound to the Inovelli switch."
      selector:
        entity:
          domain: timer
    switch_device:
      name: Switch device
      description: "The switch that will be bound to the timer. Note: This must be a Blue Series switch."
      selector:
        device:
          manufacturer: Inovelli
    led_script:
      name: LED script
      description: "The entity name for kschlichter's LED script."
      default: "script.inovelli_led"
      selector:
        entity:
          domain: script
    duration_max:
      name: Maximum duration
      description: "The maximum duration of the timer. This is used to scale the LED bar, as well as to prevent increasing the duration beyond a reasonable limit."
      default:
        minutes: 30
      selector:
        duration:
    duration_increment:
      name: Incremental duration
      description: "The incremental duration added or removed when the switch is pressed. Use 0 to disable changing the timer."
      default:
        minutes: 5
      selector:
        duration:
    update_interval:
      name: Update interval
      description: "The interval at which the LED bar will be updated. Lower values may cause significant Zigbee network traffic. Set to 0 to disable ramping down the brightness of the top LED."
      default:
        seconds: 15
      selector:
        duration:
    running_color:
      name: Running color
      description: "The color of the LED bar while the timer is running."
      default: "blue"
      selector:
        text:
    running_effect:
      name: Effect
      description: "The effect for the LEDs while the timer is running."
      default: "slow blink"
      selector:
        text:
    paused_color:
      name: Paused color
      description: "The color of the LED bar while the timer is paused."
      default: "red"
      selector:
        text:
    paused_effect:
      name: Effect
      description: "The effect for the LEDs while the timer is paused."
      default: "pulse"
      selector:
        text:
    control_load:
      name: Control load
      description: "Whether to turn the load on when starting the timer, and off when stopping the timer."
      default: true
      selector:
        boolean:
    control_other_entities:
      name: Other entities to control
      description: "A list of entities to control when the timer is started or stopped. (optional)"
      selector:
        entity:
          multiple: true
          filter:
            domain:
              - light
              - switch
              - fan
      default: []
mode: restart
max_exceeded: silent
trigger_variables:
  timer_entity: !input timer_entity
  duration_max: !input duration_max
  duration_increment: !input duration_increment
  update_interval: !input update_interval
trigger:
  - platform: state
    entity_id: !input timer_entity
    to: "active"
    id: "timer_started"
  - platform: state
    entity_id: !input timer_entity
    to: "paused"
    id: "timer_paused"
  - platform: state
    entity_id: !input timer_entity
    to: "idle"
    id: "timer_idle"
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: up_single
    trigger: device
    id: "up_single"
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: up_double
    trigger: device
    id: "up_double"
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: down_single
    trigger: device
    id: "down_single"
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: down_double
    trigger: device
    id: "down_double"
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: config_single
    trigger: device
    id: "config_single"
variables:
  timer_entity: !input timer_entity
  switch_device: !input switch_device
  led_script: !input led_script
  duration_max: !input duration_max
  duration_increment: !input duration_increment
  update_interval: !input update_interval
  running_color: !input running_color
  running_effect: !input running_effect
  paused_color: !input paused_color
  paused_effect: !input paused_effect
  control_load: !input control_load
  control_other_entities: !input control_other_entities
  max_seconds: "{{ timedelta(**duration_max).total_seconds() }}"
  increment_seconds: "{{ timedelta(**duration_increment).total_seconds() }}"
  update_seconds: "{{ timedelta(**update_interval).total_seconds() }}"
action:
  - choose:
      # ==================== TIMER STATE CHANGES ====================
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: "timer_started"
              - condition: trigger
                id: "timer_paused"
        sequence:
          # Turn on load and other entities
          - if:
              - condition: trigger
                id: "timer_started"
            then:
              - if:
                  - condition: template
                    value_template: "{{ control_load }}"
                then:
                  - service: homeassistant.turn_on
                    target:
                      device_id: !input switch_device
              - if:
                  - condition: template
                    value_template: "{{ control_other_entities is defined and control_other_entities | length > 0 }}"
                then:
                  - service: homeassistant.turn_on
                    target:
                      entity_id: "{{ control_other_entities }}"
          # Start LED update loop
          - repeat:
              sequence:
                - variables:
                    remaining_seconds: >
                      {{ (as_timestamp(state_attr(timer_entity, 'finishes_at')) - now().timestamp()) | int }}
                    # Calculate LED bar level (1-7 LEDs)
                    fraction: "{{ remaining_seconds / max_seconds }}"
                    led_count: "{{ (fraction * 7) | round(0, 'ceil') | int }}"
                    # Calculate brightness of top LED based on position within its segment
                    segment_size: "{{ max_seconds / 7 }}"
                    position_in_segment: "{{ remaining_seconds - ((led_count - 1) * segment_size) }}"
                    top_led_brightness: "{{ 10.0 if update_seconds == 0 else ((position_in_segment / segment_size) * 10) | float }}"
                    color: "{{ running_color if trigger.id == 'timer_started' else paused_color }}"
                    effect: "{{ running_effect if trigger.id == 'timer_started' else paused_effect }}"
                    next_update: "{{ update_seconds if update_seconds > 0 else remaining_seconds % segment_size }}"
                - action: "{{ led_script }}"
                  data:
                    device: !input switch_device
                    LEDnumber_effect: "LED {{ led_count }}"
                    color: "{{ color }}"
                    effect: "{{ effect }}"
                    brightness: "{{ [top_led_brightness, 10.0] | max }}"
                    duration: "indefinitely"
                # Fill in lower LEDs at full brightness
                - repeat:
                    count: "{{ led_count - 1 }}"
                    sequence:
                      - action: "{{ led_script }}"
                        data:
                          device: !input switch_device
                          LEDnumber_effect: "LED {{ repeat.index }}"
                          color: "{{ color }}"
                          effect: "{{ effect }}"
                          brightness: 10.0
                          duration: "indefinitely"
                # Clear LEDs above current level
                - repeat:
                    count: "{{ 7 - led_count }}"
                    sequence:
                      - action: "{{ led_script }}"
                        data:
                          device: !input switch_device
                          LEDnumber_effect: "LED {{ led_count + repeat.index }}"
                - if:
                  - condition: trigger
                    id: "timer_started"
                  then:
                    - wait_for_trigger:
                        - platform: state
                          entity_id: !input timer_entity
                      timeout: "{{ next_update }}"
              until:
                - condition: not
                  conditions:
                  - condition: state
                    entity_id: !input timer_entity
                    state: "active"
      - conditions:
          - condition: trigger
            id: "timer_idle"
        sequence:
          # Turn off load and other entities
          - if:
              - condition: template
                value_template: "{{ control_load }}"
            then:
              - service: homeassistant.turn_off
                target:
                  device_id: !input switch_device
          - if:
              - condition: template
                value_template: "{{ control_other_entities is defined and control_other_entities | length > 0 }}"
            then:
              - service: homeassistant.turn_off
                target:
                  entity_id: "{{ control_other_entities }}"
          # Clear all LEDs
          - repeat:
              count: 7
              sequence:
                - action: "{{ led_script }}"
                  data:
                    device: !input switch_device
                    LEDnumber_effect: "LED {{ repeat.index }}"

      # ==================== BUTTON PRESSES ====================
      - conditions:
          - condition: trigger
            id: "up_single"
        sequence:
          - choose:
              # Timer is idle: start with increment duration
              - conditions:
                  - condition: state
                    entity_id: !input timer_entity
                    state: "idle"
                sequence:
                  - service: timer.start
                    target:
                      entity_id: !input timer_entity
                    data:
                      duration: "{{ increment_seconds }}"
              # Timer is running: add increment
              - conditions:
                  - condition: state
                    entity_id: !input timer_entity
                    state: "active"
                sequence:
                  - variables:
                      remaining_seconds: >
                        {{ (as_timestamp(state_attr(timer_entity, 'finishes_at')) - now().timestamp()) | int }}
                      new_duration: "{{ [remaining_seconds + increment_seconds, max_seconds] | min }}"
                  - service: timer.start
                    target:
                      entity_id: !input timer_entity
                    data:
                      duration: "{{ new_duration }}"
              # Timer is paused: resume
              - conditions:
                  - condition: state
                    entity_id: !input timer_entity
                    state: "paused"
                sequence:
                  - service: timer.start
                    target:
                      entity_id: !input timer_entity

      - conditions:
          - condition: trigger
            id: "up_double"
        sequence:
          # Start or set to max duration
          - service: timer.start
            target:
              entity_id: !input timer_entity
            data:
              duration: "{{ max_seconds }}"

      - conditions:
          - condition: trigger
            id: "down_single"
        sequence:
          - choose:
              # Timer is running: decrease by increment
              - conditions:
                  - condition: state
                    entity_id: !input timer_entity
                    state: "active"
                sequence:
                  - variables:
                      remaining_seconds: >
                        {{ (as_timestamp(state_attr(timer_entity, 'finishes_at')) - now().timestamp()) | int }}
                      new_duration: "{{ [remaining_seconds - increment_seconds, 0] | max }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ new_duration > 0 }}"
                        sequence:
                          - service: timer.start
                            target:
                              entity_id: !input timer_entity
                            data:
                              duration: "{{ new_duration }}"
                    default:
                      - service: timer.cancel
                        target:
                          entity_id: !input timer_entity
              # Timer is paused: cancel
              - conditions:
                  - condition: state
                    entity_id: !input timer_entity
                    state: "paused"
                sequence:
                  - service: timer.cancel
                    target:
                      entity_id: !input timer_entity

      - conditions:
          - condition: trigger
            id: "down_double"
        sequence:
          # Cancel timer immediately
          - service: timer.cancel
            target:
              entity_id: !input timer_entity

      - conditions:
          - condition: trigger
            id: "config_single"
        sequence:
          - choose:
              # Timer is running: pause
              - conditions:
                  - condition: state
                    entity_id: !input timer_entity
                    state: "active"
                sequence:
                  - service: timer.pause
                    target:
                      entity_id: !input timer_entity
              # Timer is paused: resume
              - conditions:
                  - condition: state
                    entity_id: !input timer_entity
                    state: "paused"
                sequence:
                  - service: timer.start
                    target:
                      entity_id: !input timer_entity